### ISSUE TITLE
License

### ISSUE THREAD

**Issue by msanders** [jerrymarino/SwiftPlayground.vim#4]
Does this project have a license? Interested in using the foundation to port over to another editor :slightly_smiling_face:

**Comment by jerrymarino** [comment]
Hey @msanders - sorry for the delayed response, I'm just getting back to things from vacation. As of today, there is no license. I'd prefer something permissive and compatible with other permissive ones: perhaps BSD is a good fit. I'm not sure of any downsides to that.

Overall, I think it'd be awesome to use this with other editors - the current system is pretty simple:
- a simple runtime for emitting code.
- a bash script for a build system.

None the less, this has been useful for my own development workflow. In the future, I plan to make more features - like SwiftPackageManager integration and more.

**Comment by msanders** [comment]
A BSD license sounds reasonable. Was unsure if I could use it since not having a license generally means it's copyrighted. Thanks for the great tool! The Swift <=> Vim work all looks super promising.

**Comment by jerrymarino** [comment]
@msanders thank you, for the kind words! It's super cool to see the community adding Swift support into other editors. I'm taking into consideration how the Swift Vim features I'm building can be made in a way that are as decoupled from Vim as much as possible.

I'll push a BSD license to this and other related projects. Cheers 👍
